---
- hosts: neofetch_hosts

  tasks:
    - name: Install neofetch
      ansible.builtin.package:
        name: neofetch
        state: present

    - name: Delete local config
      become: true
      ansible.builtin.file:
        path: /etc/neofetch/
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Create neofetch configuration file.
      become: true
      ansible.builtin.template:
        src: templates/config.conf.j2
        dest: "/etc/neofetch/config.conf"
        mode: '0644'

    - name: Also add user config
      ansible.builtin.template:
        src: templates/config.conf.j2
        dest: "{{ ansible_env.HOME }}/.config/neofetch/config.conf"
        mode: '0640'

    - name: Create neofetch message of the day
      ansible.builtin.template:
        src: templates/01-neofetch.j2
        dest: "/etc/update-motd.d/01-neofetch"
        mode: '0755'
      become: true
